### ISSUE TITLE
Error on saving options preference

### ISSUE THREAD

**Issue by SoulDev64** [SoulDev64/NikonCapture#5]
For specific options, the App doesn't allow to save the new selection for a choice.

This is the debug:

> {'image': '',
>  'open': 0,
>  'tags': '',
>  'text': 'capturesettings',
>  'values': ["> Réglages de capture d'image", '', '']}
> {'image': '',
>  'open': 0,
>  'tags': ['rw'],
>  'text': 'focusmode2',
>  'values': ['focusmode2', '   Mode de mise au point 2', 'AF-A']}
> <Swig Object of type '_CameraWidget *' at 0x105620af0>
> -->
> 5
> 'AF-S'
> 'AF-C'
> 'AF-A'
> 'MF (fixe)'
> 'MF (sélection)'
> ['AF-S', 'AF-C', 'AF-A', 'MF (fixe)', 'MF (sélection)']
> clicked
> <Swig Object of type '_CameraWidget *' at 0x105617b30>
> set response: AF-S
> Exception in Tkinter callback
> Traceback (most recent call last):
>   File "/opt/homebrew/Cellar/python@3.9/3.9.13_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/tkinter/__init__.py", line 1892, in __call__
>     return self.func(*args)
>   File "/NikonCapture/ConfigurationUX.py", line 208, in saveOption
>     res = (self.camera.set_single_config(config_name, config_widget))
> gphoto2.GPhoto2Error: [-2] Mauvais paramètres

**Comment by SoulDev64** [comment]
Depending on the mode selected on the camera, some options cannot be changed via USB. I am trying to indicate this fact more precisely in the App.
